                <!-- 正文サイトバー部分 -->
                <div id="st_mn_ct_side">
                    <div class="uk-flex uk-flex-column uk-flex-top">
                        <div class="st_mn_ct_sd_works uk-flex uk-flex-column">
                        <a target="_blank" rel="noopener noreferrer" href="./standalone/JIMUCTI/loader.html" class="st_mn_ct_sd_wk_img">
                            <img src="./image/others/JIMCHI.png" alt="JIMCHI">
                        </a>
                        <div class="st_mn_ct_sd_wk_info uk-flex uk-flex-column uk-flex-middle">
                            <span class="st_mn_ct_sd_wk_inf_title">
                                JIMCHIサイト制作しました。↓
                            </span>
                            <a target="_blank" rel="noopener noreferrer" href="./standalone/JIMUCTI/loader.html" class="st_mn_ct_sd_wk_inf_link"></a>
                        </div>
                    </div>
                    <div class="st_mn_ct_sd_works uk-flex uk-flex-column">
                        <a target="_blank" rel="noopener noreferrer" href="#" class="st_mn_ct_sd_wk_img">
                            <img src="./image/poster/grapes.jpg" alt="">
                        </a>
                        <div class="st_mn_ct_sd_wk_info uk-flex uk-flex-column uk-flex-middle">
                            <span class="st_mn_ct_sd_wk_inf_title">
                                季節限定ハンドクリーム
                            </span>
                            <a target="_blank" rel="noopener noreferrer" href="#" class="st_mn_ct_sd_wk_inf_link"></a>
                        </div>
                    </div>
                    <div class="st_mn_ct_sd_works uk-flex uk-flex-column">
                        <a target="_blank" rel="noopener noreferrer" href="./game/diffcat.php" class="st_mn_ct_sd_wk_img">
                            <img src="./image/others/spot-the-difference.png" alt="">
                        </a>
                        <div class="st_mn_ct_sd_wk_info uk-flex uk-flex-column uk-flex-middle">
                            <span class="st_mn_ct_sd_wk_inf_title">
                                ↑やってみる？
                            </span>
                            <a target="_blank" rel="noopener noreferrer" href="" class="st_mn_ct_sd_wk_inf_link"></a>
                        </div>
                    </div>
                    <div class="st_mn_ct_sd_works uk-flex uk-flex-column">
                        <a target="_blank" rel="noopener noreferrer" href="#" class="st_mn_ct_sd_wk_img">
                            <img src="./image/others/exhibition.jpg" alt="">
                        </a>
                        <div class="st_mn_ct_sd_wk_info uk-flex uk-flex-column uk-flex-middle">
                            <span class="st_mn_ct_sd_wk_inf_title">
                                作品展示会が開催決定!
                            </span>
                            <a target="_blank" rel="noopener noreferrer" href="#" class="st_mn_ct_sd_wk_inf_link"></a>
                        </div>
                    </div>
                    <div class="st_mn_ct_sd_works uk-flex uk-flex-column">
                        <a target="_blank" rel="noopener noreferrer" href="./standalone/PDF/portfolio.pdf" class="st_mn_ct_sd_wk_img">
                            <img src="./image/others/portfolio.png" alt="">
                        </a>
                        <div class="st_mn_ct_sd_wk_info uk-flex uk-flex-column uk-flex-middle">
                            <span class="st_mn_ct_sd_wk_inf_title"></span>
                            <a target="_blank" rel="noopener noreferrer" href="./standalone/PDF/portfolio.pdf" class="st_mn_ct_sd_wk_inf_link">
                                中身を見る
                            </a>
                        </div>
                    </div>
                    <div class="st_mn_ct_sd_works uk-flex uk-flex-column">
                        <a target="_blank" rel="noopener noreferrer" href="https://store.line.me/stickershop/product/31223760/ja" class="st_mn_ct_sd_wk_img">
                            <img src="./image/others/LINE-stamp.png" alt="">
                        </a>
                        <div class="st_mn_ct_sd_wk_info uk-flex uk-flex-column uk-flex-middle">
                            <span class="st_mn_ct_sd_wk_inf_title">
                                LINEスタンプ<br>好評発売中↓
                            </span>
                            <a target="_blank" rel="noopener noreferrer" href="https://store.line.me/stickershop/product/31223760/ja" class="st_mn_ct_sd_wk_inf_link">
                                購入はこちらから
                            </a>
                        </div>
                    </div>
                    </div>
                </div>

                <!-- 正文メイン部分 -->
                <div id="st_mn_ct_main">
                    <!-- お知らせ部分 -->
                    <section id="st_mn_ct_mn_notice">
                        <div id="st_mn_ct_mn_n_title" class="uk-flex uk-flex-middle uk-flex-center">
                            <span>作品一覧（制作順）</span>
                        </div>
                        <div id="st_mn_ct_mn_n_list" class="uk-flex uk-flex-center" uk-grid>
    <div class="st_mn_ct_mn_n_ls_card">
        <a class="st_mn_ct_mn_n_ls_c_link uk-flex uk-flex-middle" target="_blank" rel="noopener noreferrer" href="./work/10">
            <img class="st_mn_ct_mn_n_ls_c_l_img" src="./image/gallery/1.png" alt="名刺">
            <div class="uk-flex uk-flex-column">
                <h4 class="st_mn_ct_mn_n_ls_c_l_title">名刺</h4>
                <p class="st_mn_ct_mn_n_ls_c_l_info">名刺交換に使える。</p>
            </div>
        </a>
    </div>

    <div class="st_mn_ct_mn_n_ls_card">
        <a class="st_mn_ct_mn_n_ls_c_link uk-flex uk-flex-middle" target="_blank" rel="noopener noreferrer" href="./work/1">
            <img class="st_mn_ct_mn_n_ls_c_l_img" src="./image/gallery/2.png" alt="Tシャツ">
            <div class="uk-flex uk-flex-column">
				<h4 class="st_mn_ct_mn_n_ls_c_l_title">Tシャツ</h4>
                <p class="st_mn_ct_mn_n_ls_c_l_info">「音×宇宙」をテーマにしたＴシャツ。パンツと合わせると良い。</p>
			</div>
        </a>
    </div>

    <div class="st_mn_ct_mn_n_ls_card">
        <a class="st_mn_ct_mn_n_ls_c_link uk-flex uk-flex-middle" target="_blank" rel="noopener noreferrer" href="./work/5">
            <img class="st_mn_ct_mn_n_ls_c_l_img" src="./image/gallery/3.png" alt="ハンドクリーム桃">
            <div class="uk-flex uk-flex-column">
				<h4 class="st_mn_ct_mn_n_ls_c_l_title">ハンドクリーム桃</h4>
                <p class="st_mn_ct_mn_n_ls_c_l_info">夏限定のハンドクリーム。桃の香りがする。</p>
			</div>
        </a>
    </div>

    <div class="st_mn_ct_mn_n_ls_card">
        <a class="st_mn_ct_mn_n_ls_c_link uk-flex uk-flex-middle" target="_blank" rel="noopener noreferrer" href="./work/9">
            <img class="st_mn_ct_mn_n_ls_c_l_img" src="./image/gallery/4.png" alt="きのにゃんのLINEスタンプ">
            <div class="uk-flex uk-flex-column">
				<h4 class="st_mn_ct_mn_n_ls_c_l_title">きのにゃんのLINEスタンプ</h4>
                <p class="st_mn_ct_mn_n_ls_c_l_info">日常で使えるLINEスタンプ。実際にLINEストアで買える。</p>
			</div>
        </a>
    </div>

    <div class="st_mn_ct_mn_n_ls_card">
        <a class="st_mn_ct_mn_n_ls_c_link uk-flex uk-flex-middle" target="_blank" rel="noopener noreferrer" href="./work/3">
            <img class="st_mn_ct_mn_n_ls_c_l_img" src="./image/gallery/5.png" alt="kinonyaのロゴ">
            <div class="uk-flex uk-flex-column">
				<h4 class="st_mn_ct_mn_n_ls_c_l_title">kinonyaのロゴ</h4>
                <p class="st_mn_ct_mn_n_ls_c_l_info">このサイトで使われているロゴ。</p>
			</div>
        </a>
    </div>

    <div class="st_mn_ct_mn_n_ls_card">
        <a class="st_mn_ct_mn_n_ls_c_link uk-flex uk-flex-middle" target="_blank" rel="noopener noreferrer" href="./work/4">
            <img class="st_mn_ct_mn_n_ls_c_l_img" src="./image/gallery/6.png" alt="ハンドクリーム苺">
            <div class="uk-flex uk-flex-column">
				<h4 class="st_mn_ct_mn_n_ls_c_l_title">ハンドクリーム苺</h4>
                <p class="st_mn_ct_mn_n_ls_c_l_info">春限定のハンドクリーム。苺の香りがする。</p>
			</div>
        </a>
    </div>

    <div class="st_mn_ct_mn_n_ls_card">
        <a class="st_mn_ct_mn_n_ls_c_link uk-flex uk-flex-middle" target="_blank" rel="noopener noreferrer" href="./work/6">
            <img class="st_mn_ct_mn_n_ls_c_l_img" src="./image/gallery/7.png" alt="ハンドクリームぶどう">
            <div class="uk-flex uk-flex-column">
				<h4 class="st_mn_ct_mn_n_ls_c_l_title">ハンドクリームぶどう</h4>
                <p class="st_mn_ct_mn_n_ls_c_l_info">秋限定のハンドクリーム。ぶどうの香りがする。</p>
			</div>
        </a>
    </div>

    <div class="st_mn_ct_mn_n_ls_card">
        <a class="st_mn_ct_mn_n_ls_c_link uk-flex uk-flex-middle" target="_blank" rel="noopener noreferrer" href="./work/7">
            <img class="st_mn_ct_mn_n_ls_c_l_img" src="./image/gallery/8.png" alt="ハンドクリームレモン">
            <div class="uk-flex uk-flex-column">
				<h4 class="st_mn_ct_mn_n_ls_c_l_title">ハンドクリームレモン</h4>
                <p class="st_mn_ct_mn_n_ls_c_l_info">冬限定のハンドクリーム。レモンの香りがする。</p>
			</div>
        </a>
    </div>

    <div class="st_mn_ct_mn_n_ls_card">
        <a class="st_mn_ct_mn_n_ls_c_link uk-flex uk-flex-middle" target="_blank" rel="noopener noreferrer" href="./work/11">
            <img class="st_mn_ct_mn_n_ls_c_l_img" src="./image/gallery/9.png" alt="HIPHOPかるた箱">
            <div class="uk-flex uk-flex-column">
				<h4 class="st_mn_ct_mn_n_ls_c_l_title">HIPHOPかるた箱</h4>
                <p class="st_mn_ct_mn_n_ls_c_l_info">作品展示会で制作したオリジナルかるたの箱。<br>102枚のカードが入っており、実際に遊べる。</p>
			</div>
        </a>
    </div>

    <div class="st_mn_ct_mn_n_ls_card">
        <a class="st_mn_ct_mn_n_ls_c_link uk-flex uk-flex-middle" target="_blank" rel="noopener noreferrer" href="./work/12">
            <img class="st_mn_ct_mn_n_ls_c_l_img" src="./image/gallery/10.png" alt="HIPHOPかるたカード">
            <div class="uk-flex uk-flex-column">
				<h4 class="st_mn_ct_mn_n_ls_c_l_title">HIPHOPかるたカード</h4>
                <p class="st_mn_ct_mn_n_ls_c_l_info">作品展示会で制作したオリジナルかるたのカード。<br>102枚のカードが入っており、実際に遊べる。</p>
			</div>
        </a>
    </div>

    <div class="st_mn_ct_mn_n_ls_card">
        <a class="st_mn_ct_mn_n_ls_c_link uk-flex uk-flex-middle" target="_blank" rel="noopener noreferrer" href="./work/2">
            <img class="st_mn_ct_mn_n_ls_c_l_img" src="./image/gallery/11.png" alt="パンツ">
            <div class="uk-flex uk-flex-column">
				<h4 class="st_mn_ct_mn_n_ls_c_l_title">パンツ</h4>
                <p class="st_mn_ct_mn_n_ls_c_l_info">深海→空→夜空のグラデーションのパンツ。Tシャツと合わせると良い。</p>
			</div>
        </a>
    </div>

    <div class="st_mn_ct_mn_n_ls_card">
        <a class="st_mn_ct_mn_n_ls_c_link uk-flex uk-flex-middle" target="_blank" rel="noopener noreferrer" href="./work/13">
            <img class="st_mn_ct_mn_n_ls_c_l_img" src="./image/gallery/12.png" alt="入浴剤">
            <div class="uk-flex uk-flex-column">
				<h4 class="st_mn_ct_mn_n_ls_c_l_title">入浴剤</h4>
                <p class="st_mn_ct_mn_n_ls_c_l_info">季節の入浴剤。春夏秋冬の香りが楽しめる。</p>
			</div>
        </a>
    </div>

    <div class="st_mn_ct_mn_n_ls_card">
        <a class="st_mn_ct_mn_n_ls_c_link uk-flex uk-flex-middle" target="_blank" rel="noopener noreferrer" href="./work/8">
            <img class="st_mn_ct_mn_n_ls_c_l_img" src="./image/gallery/13.png" alt="ロゴ２">
            <div class="uk-flex uk-flex-column">
				<h4 class="st_mn_ct_mn_n_ls_c_l_title">kinonyaのロゴ２</h4>
                <p class="st_mn_ct_mn_n_ls_c_l_info">ロゴ２つ目。このサイトで使われている。</p>
			</div>
        </a>
    </div>

    <div class="st_mn_ct_mn_n_ls_card">
        <a class="st_mn_ct_mn_n_ls_c_link uk-flex uk-flex-middle" target="_blank" rel="noopener noreferrer" href="./work/14">
            <img class="st_mn_ct_mn_n_ls_c_l_img" src="./image/gallery/14.png" alt="ポートフォリオ集">
            <div class="uk-flex uk-flex-column">
				<h4 class="st_mn_ct_mn_n_ls_c_l_title">ポートフォリオ集</h4>
                <p class="st_mn_ct_mn_n_ls_c_l_info">作品集。今までの作品が収録されてる。</p>
			</div>
        </a>
    </div>
                        </div>
                    </section>
                </div>