                <!-- 正文サイトバー部分 -->
                <div id="st_mn_ct_side">
                    <div class="uk-flex uk-flex-column uk-flex-top">
                        <div class="st_mn_ct_sd_works uk-flex uk-flex-column">
                        <a href="./standalone/JIMUCTI/loader.html" class="st_mn_ct_sd_wk_img">
                            <img src="./image/others/JIMCHI.png" alt="JIMCHI">
                        </a>
                        <div class="st_mn_ct_sd_wk_info uk-flex uk-flex-column uk-flex-middle">
                            <span class="st_mn_ct_sd_wk_inf_title">
                                JIMCHIサイト制作しました。↓
                            </span>
                            <a href="./standalone/JIMUCTI/loader.html" class="st_mn_ct_sd_wk_inf_link"></a>
                        </div>
                    </div>
                    <div class="st_mn_ct_sd_works uk-flex uk-flex-column">
                        <a href="#" class="st_mn_ct_sd_wk_img">
                            <img src="./image/poster/grapes.jpg" alt="">
                        </a>
                        <div class="st_mn_ct_sd_wk_info uk-flex uk-flex-column uk-flex-middle">
                            <span class="st_mn_ct_sd_wk_inf_title">
                                季節限定ハンドクリーム
                            </span>
                            <a href="#" class="st_mn_ct_sd_wk_inf_link"></a>
                        </div>
                    </div>
                    <div class="st_mn_ct_sd_works uk-flex uk-flex-column">
                        <a href="./game/diffcat.php" class="st_mn_ct_sd_wk_img">
                            <img src="./image/others/spot-the-difference.png" alt="">
                        </a>
                        <div class="st_mn_ct_sd_wk_info uk-flex uk-flex-column uk-flex-middle">
                            <span class="st_mn_ct_sd_wk_inf_title">
                                ↑やってみる？
                            </span>
                            <a href="" class="st_mn_ct_sd_wk_inf_link"></a>
                        </div>
                    </div>
                    <div class="st_mn_ct_sd_works uk-flex uk-flex-column">
                        <a href="#" class="st_mn_ct_sd_wk_img">
                            <img src="./image/others/exhibition.jpg" alt="">
                        </a>
                        <div class="st_mn_ct_sd_wk_info uk-flex uk-flex-column uk-flex-middle">
                            <span class="st_mn_ct_sd_wk_inf_title">
                                作品展示会が開催決定!
                            </span>
                            <a href="#" class="st_mn_ct_sd_wk_inf_link"></a>
                        </div>
                    </div>
                    <div class="st_mn_ct_sd_works uk-flex uk-flex-column">
                        <a href="./standalone/PDF/portfolio.pdf" class="st_mn_ct_sd_wk_img">
                            <img src="./image/others/portfolio.png" alt="">
                        </a>
                        <div class="st_mn_ct_sd_wk_info uk-flex uk-flex-column uk-flex-middle">
                            <span class="st_mn_ct_sd_wk_inf_title"></span>
                            <a href="./standalone/PDF/portfolio.pdf" class="st_mn_ct_sd_wk_inf_link">
                                中身を見る
                            </a>
                        </div>
                    </div>
                    <div class="st_mn_ct_sd_works uk-flex uk-flex-column">
                        <a href="https://store.line.me/stickershop/product/31223760/ja" class="st_mn_ct_sd_wk_img">
                            <img src="./image/others/LINE-stamp.png" alt="">
                        </a>
                        <div class="st_mn_ct_sd_wk_info uk-flex uk-flex-column uk-flex-middle">
                            <span class="st_mn_ct_sd_wk_inf_title">
                                LINEスタンプ<br>好評発売中↓
                            </span>
                            <a href="https://store.line.me/stickershop/product/31223760/ja" class="st_mn_ct_sd_wk_inf_link">
                                購入はこちらから
                            </a>
                        </div>
                    </div>
                    </div>
                </div>

                <!-- 正文メイン部分 -->
                <div id="st_mn_ct_main">
                    <!-- お知らせ部分 -->
                    <section id="st_mn_ct_mn_notice">
                        <div id="st_mn_ct_mn_n_title" class="uk-flex uk-flex-middle uk-flex-center">
                            <span>作品一覧（制作順）</span>
                        </div>
                        <div id="st_mn_ct_mn_n_list" class="work-list-wrap">
	<div class="list">
		<a href="./work/10">
			<figure><img src="./image/gallery/1.png" alt="名刺"></figure>
			<h4>名刺</h4>
			<p>名刺交換に使える。</p>
		</a>
	</div>

	<div class="list">
		<a href="./work/1">
			<figure><img src="./image/gallery/2.png" alt="Tシャツ"></figure>
			<h4>Tシャツ</h4>
			<p>「音×宇宙」をテーマにしたＴシャツ。パンツと合わせると良い。</p>
		</a>
	</div>

	<div class="list">
		<a href="./work/5">
			<figure><img src="./image/gallery/3.png" alt="ハンドクリーム桃"></figure>
			<h4>ハンドクリーム桃</h4>
			<p>夏限定のハンドクリーム。桃の香りがする。</p>
		</a>
	</div>

	<div class="list">
		<a href="./work/9">
			<figure><img src="./image/gallery/4.png" alt="きのにゃんのLINEスタンプ"></figure>
			<h4>きのにゃんのLINEスタンプ</h4>
			<p>日常で使えるLINEスタンプ。実際にLINEストアで買える。</p>
		</a>
	</div>

	<div class="list">
		<a href="./work/3">
			<figure><img src="./image/gallery/5.png" alt="kinonyaのロゴ"></figure>
			<h4>kinonyaのロゴ</h4>
			<p>このサイトで使われているロゴ。</p>
		</a>
	</div>

	<div class="list">
		<a href="./work/4">
			<figure><img src="./image/gallery/6.png" alt="ハンドクリーム苺"></figure>
			<h4>ハンドクリーム苺</h4>
			<p>春限定のハンドクリーム。苺の香りがする。</p>
		</a>
	</div>

	<div class="list">
		<a href="./work/6">
			<figure><img src="./image/gallery/7.png" alt="ハンドクリームぶどう"></figure>
			<h4>ハンドクリームぶどう</h4>
			<p>秋限定のハンドクリーム。ぶどうの香りがする。</p>
		</a>
	</div>

	<div class="list">
		<a href="./work/7">
			<figure><img src="./image/gallery/8.png" alt="ハンドクリームレモン"></figure>
			<h4>ハンドクリームレモン</h4>
			<p>冬限定のハンドクリーム。レモンの香りがする。</p>
		</a>
	</div>

	<div class="list">
		<a href="./work/11">
			<figure><img src="./image/gallery/9.png" alt="HIPHOPかるた箱"></figure>
			<h4>HIPHOPかるた箱</h4>
			<p>作品展示会で制作したオリジナルかるたの箱。<br>102枚のカードが入っており、実際に遊べる。</p>
		</a>
	</div>

	<div class="list">
		<a href="./work/12">
			<figure><img src="./image/gallery/10.png" alt="HIPHOPかるたカード"></figure>
			<h4>HIPHOPかるたカード</h4>
			<p>作品展示会で制作したオリジナルかるたのカード。<br>102枚のカードが入っており、実際に遊べる。</p>
		</a>
	</div>

	<div class="list">
		<a href="./work/2">
			<figure><img src="./image/gallery/11.png" alt="パンツ"></figure>
			<h4>パンツ</h4>
			<p>深海→空→夜空のグラデーションのパンツ。Tシャツと合わせると良い。</p>
		</a>
	</div>

	<div class="list">
		<a href="./work/13">
			<figure><img src="./image/gallery/12.png" alt="入浴剤"></figure>
			<h4>入浴剤</h4>
			<p>季節の入浴剤。春夏秋冬の香りが楽しめる。</p>
		</a>
	</div>

	<div class="list">
		<a href="./work/8">
			<figure><img src="./image/gallery/13.png" alt="ロゴ２"></figure>
			<h4>kinonyaのロゴ２</h4>
			<p>ロゴ２つ目。このサイトで使われている。</p>
		</a>
	</div>

	<div class="list">
		<a href="./work/14">
			<figure><img src="./image/gallery/14.png" alt="ポートフォリオ集"></figure>
			<h4>ポートフォリオ集</h4>
			<p>作品集。今までの作品が収録されてる。</p>
		</a>
	</div>
                        </div>
                    </section>
                </div>