                <!-- 正文サイトバー部分 -->
                <div id="st_mn_ct_side">
                    <div class="uk-flex uk-flex-column uk-flex-top">
                        <div class="st_mn_ct_sd_works uk-flex uk-flex-column">
                        <a href="./standalone/JIMUCTI/loader.html" class="st_mn_ct_sd_wk_img">
                            <img src="./image/others/JIMCHI.png" alt="JIMCHI">
                        </a>
                        <div class="st_mn_ct_sd_wk_info uk-flex uk-flex-column uk-flex-middle">
                            <span class="st_mn_ct_sd_wk_inf_title">
                                JIMCHIサイト制作しました。↓
                            </span>
                            <a href="./standalone/JIMUCTI/loader.html" class="st_mn_ct_sd_wk_inf_link"></a>
                        </div>
                    </div>
                    <div class="st_mn_ct_sd_works uk-flex uk-flex-column">
                        <a href="#" class="st_mn_ct_sd_wk_img">
                            <img src="./image/poster/grapes.jpg" alt="">
                        </a>
                        <div class="st_mn_ct_sd_wk_info uk-flex uk-flex-column uk-flex-middle">
                            <span class="st_mn_ct_sd_wk_inf_title">
                                季節限定ハンドクリーム
                            </span>
                            <a href="#" class="st_mn_ct_sd_wk_inf_link"></a>
                        </div>
                    </div>
                    <div class="st_mn_ct_sd_works uk-flex uk-flex-column">
                        <a href="./game/diffcat.php" class="st_mn_ct_sd_wk_img">
                            <img src="./image/others/spot-the-difference.png" alt="">
                        </a>
                        <div class="st_mn_ct_sd_wk_info uk-flex uk-flex-column uk-flex-middle">
                            <span class="st_mn_ct_sd_wk_inf_title">
                                ↑やってみる？
                            </span>
                            <a href="" class="st_mn_ct_sd_wk_inf_link"></a>
                        </div>
                    </div>
                    <div class="st_mn_ct_sd_works uk-flex uk-flex-column">
                        <a href="#" class="st_mn_ct_sd_wk_img">
                            <img src="./image/others/exhibition.jpg" alt="">
                        </a>
                        <div class="st_mn_ct_sd_wk_info uk-flex uk-flex-column uk-flex-middle">
                            <span class="st_mn_ct_sd_wk_inf_title">
                                作品展示会が開催決定!
                            </span>
                            <a href="#" class="st_mn_ct_sd_wk_inf_link"></a>
                        </div>
                    </div>
                    <div class="st_mn_ct_sd_works uk-flex uk-flex-column">
                        <a href="./portfolio" class="st_mn_ct_sd_wk_img">
                            <img src="./image/others/portfolio.png" alt="">
                        </a>
                        <div class="st_mn_ct_sd_wk_info uk-flex uk-flex-column uk-flex-middle">
                            <span class="st_mn_ct_sd_wk_inf_title"></span>
                            <a href="./standalone/PDF/portfolio.pdf" class="st_mn_ct_sd_wk_inf_link">
                                中身を見る
                            </a>
                        </div>
                    </div>
                    <div class="st_mn_ct_sd_works uk-flex uk-flex-column">
                        <a href="https://store.line.me/stickershop/product/31223760/ja" class="st_mn_ct_sd_wk_img">
                            <img src="./image/others/LINE-stamp.png" alt="">
                        </a>
                        <div class="st_mn_ct_sd_wk_info uk-flex uk-flex-column uk-flex-middle">
                            <span class="st_mn_ct_sd_wk_inf_title">
                                LINEスタンプ<br>好評発売中↓
                            </span>
                            <a href="https://store.line.me/stickershop/product/31223760/ja" class="st_mn_ct_sd_wk_inf_link">
                                購入はこちらから
                            </a>
                        </div>
                    </div>
                    </div>
                </div>

                <!-- 正文メイン部分 -->
                <div id="st_mn_ct_main">
                    <!-- お知らせ部分 -->
                    <section id="st_mn_ct_mn_notice">
                        <div id="st_mn_ct_mn_n_title" class="uk-flex uk-flex-middle uk-flex-center">
                            <span>お知らせ</span>
                        </div>
                        <div id="st_mn_ct_mn_n_list">
                            <!-- 新聞箇条 -->
                            <div class="st_mn_ct_mn_n_ls_news">
                                <!-- 一行目：日付・ラベル -->
                                <div class="st_mn_ct_mn_n_ls_n_info uk-flex uk-flex-middle">
                                    <time datetime="2026-03-23">2026/03/23</time>
                                    <span class="fc-news-tag-blank st_mn_ct_mn_n_ls_n_inf_label uk-flex uk-flex-middle uk-flex-center">
                                        ホームページ公開
                                    </span>
                                </div>
                                <!-- 二行目以降：情報 -->
                                <div class="st_mn_ct_mn_n_ls_n_text uk-flex uk-flex-column">
                                    <span>
                                        YUKINO-オンラインホームページが公開されました！
                                    </span>
                                </div>
                            </div>
                            <div class="st_mn_ct_mn_n_ls_news">
                                <div class="st_mn_ct_mn_n_ls_n_info uk-flex uk-flex-middle">
                                    <time datetime="2026-01-23">2026/01/23</time>
                                    <span class="fc-news-tag-fill st_mn_ct_mn_n_ls_n_inf_label">
                                        サイト制作
                                    </span>
                                </div>
                                <div class="st_mn_ct_mn_n_ls_n_text uk-flex uk-flex-column">
                                    <span>
                                        焼肉店JIMCH様のホームページを製作させていただきました！<a href="./standalone/JIMUCTI/loader.html"> → JIMCHIサイト</a>
                                    </span>
                                    <span>
                                        ※実案件のため一部非公開（現在クライアントと調整中）
                                    </span>
                                </div>
                            </div>
                            <div class="st_mn_ct_mn_n_ls_news">
                                <div class="st_mn_ct_mn_n_ls_n_info uk-flex uk-flex-middle">
                                    <time datetime="2025-12-16">2025/12/16</time>
                                    <span class="fc-news-tag-fill st_mn_ct_mn_n_ls_n_inf_label">
                                        ポートフォリオPDF
                                    </span>
                                </div>
                                <div class="st_mn_ct_mn_n_ls_n_text uk-flex uk-flex-column">
                                    <span>ポートフォリオのPDFを作成しました！<a href="./portfolio" target="_blank"> PDFを見る</a></span>
                                </div>
                            </div>
                        </div>
                    </section>

                    <!-- 商品部分 -->
                    <section id="st_mn_ct_mn_product">
                        <!-- グループ：季節限定ハンドクリーム -->
                        <div class="st_mn_ct_mn_pd_group uk-flex uk-flex-column uk-flex-middle">
                            <!-- グループタイトル -->
                            <div class="st_mn_ct_mn_pd_g_title uk-flex uk-flex-middle">
                                季節限定ハンドクリーム
                            </div>
                            <!-- グループリスト -->
                            <section class="st_mn_ct_mn_pd_g_list uk-flex" uk-grid>
                                <!-- 商品カードユニット -->
                                <div class="st_mn_ct_mn_pd_g_ls_work uk-flex uk-flex-column uk-flex-middle uk-width-1-3@s uk-width-1-4@m">
                                    <a href="/work/4" class="st_mn_ct_mn_pd_g_ls_wk_img"><img src="./image/top/1.png" alt=""></a>
                                    <span class="st_mn_ct_mn_pd_g_ls_wk_title">
                                        ハンドクリーム（苺の香り）
                                    </span>
                                </div>
                                <div class="st_mn_ct_mn_pd_g_ls_work uk-flex uk-flex-column uk-flex-middle uk-width-1-3@s uk-width-1-4@m">
                                    <a href="/work/5" class="st_mn_ct_mn_pd_g_ls_wk_img"><img src="./image/top/2.png" alt=""></a>
                                    <span class="st_mn_ct_mn_pd_g_ls_wk_title">
                                        ハンドクリーム（桃の香り）
                                    </span>
                                </div>
                                <div class="st_mn_ct_mn_pd_g_ls_work uk-flex uk-flex-column uk-flex-middle uk-width-1-3@s uk-width-1-4@m">
                                    <a href="/work/6" class="st_mn_ct_mn_pd_g_ls_wk_img"><img src="./image/top/3.png" alt=""></a>
                                    <span class="st_mn_ct_mn_pd_g_ls_wk_title">
                                        ハンドクリーム（ぶどうの香り）
                                    </span>
                                </div>
                                <div class="st_mn_ct_mn_pd_g_ls_work uk-flex uk-flex-column uk-flex-middle uk-width-1-3@s uk-width-1-4@m">
                                    <a href="/work/7" class="st_mn_ct_mn_pd_g_ls_wk_img"><img src="./image/top/4.png" alt=""></a>
                                    <span class="st_mn_ct_mn_pd_g_ls_wk_title">
                                        ハンドクリーム（レモンの香り）
                                    </span>
                                </div>
                            </section>
                        </div>

                        <!-- グループ：アパレル商品 -->
                        <div class="st_mn_ct_mn_pd_group uk-flex uk-flex-column uk-flex-middle">
                            <!-- グループタイトル -->
                            <div class="st_mn_ct_mn_pd_g_title uk-flex uk-flex-middle">
                                アパレル商品
                            </div>
                            <!-- グループリスト -->
                            <section class="st_mn_ct_mn_pd_g_list uk-flex" uk-grid>
                                <div class="st_mn_ct_mn_pd_g_ls_work uk-flex uk-flex-column uk-flex-middle uk-width-1-3@s uk-width-1-4@m">
                                    <a href="/work/1" class="st_mn_ct_mn_pd_g_ls_wk_img"><img src="./image/top/5.png" alt=""></a>
                                    <span class="st_mn_ct_mn_pd_g_ls_wk_title">
                                        音×自由-Tシャツ-
                                    </span>
                                </div>
                                <div class="st_mn_ct_mn_pd_g_ls_work uk-flex uk-flex-column uk-flex-middle uk-width-1-3@s uk-width-1-4@m">
                                    <a href="/work/2" class="st_mn_ct_mn_pd_g_ls_wk_img"><img src="./image/top/6.png" alt=""></a>
                                    <span class="st_mn_ct_mn_pd_g_ls_wk_title">
                                        音×自由-パンツ
                                    </span>
                                </div>
                            </section>
                        </div>

                        <!-- グループ：作品展示会用 -->
                        <div class="st_mn_ct_mn_pd_group uk-flex uk-flex-column uk-flex-middle">
                            <!-- グループタイトル -->
                            <div class="st_mn_ct_mn_pd_g_title uk-flex uk-flex-middle">
                                作品展示会用
                            </div>
                            <!-- グループリスト -->
                            <section class="st_mn_ct_mn_pd_g_list uk-flex" uk-grid>
                                <div class="st_mn_ct_mn_pd_g_ls_work uk-flex uk-flex-column uk-flex-middle uk-width-1-3@s uk-width-1-4@m">
                                    <a href="/work/11" class="st_mn_ct_mn_pd_g_ls_wk_img"><img src="./image/top/7.png" alt=""></a>
                                    <span class="st_mn_ct_mn_pd_g_ls_wk_title">
                                        HIPHOPかるた箱
                                    </span>
                                </div>
                                <div class="st_mn_ct_mn_pd_g_ls_work uk-flex uk-flex-column uk-flex-middle uk-width-1-3@s uk-width-1-4@m">
                                    <a href="/work/12" class="st_mn_ct_mn_pd_g_ls_wk_img"><img src="./image/top/8.png" alt=""></a>
                                    <span class="st_mn_ct_mn_pd_g_ls_wk_title">
                                        HIPHOPかるたカード
                                    </span>
                                </div>
                            </section>
                        </div>

                        <!-- グループ：ロゴ -->
                        <div class="st_mn_ct_mn_pd_group uk-flex uk-flex-column uk-flex-middle">
                            <!-- グループタイトル -->
                            <div class="st_mn_ct_mn_pd_g_title uk-flex uk-flex-middle">
                                ロゴ
                            </div>
                            <!-- グループリスト -->
                            <section class="st_mn_ct_mn_pd_g_list uk-flex" uk-grid>
                                <div class="st_mn_ct_mn_pd_g_ls_work uk-flex uk-flex-column uk-flex-middle uk-width-1-3@s uk-width-1-4@m">
                                    <a href="/work/3" class="st_mn_ct_mn_pd_g_ls_wk_img"><img src="./image/top/9.png" alt=""></a>
                                    <span class="st_mn_ct_mn_pd_g_ls_wk_title">
                                        ロゴ１
                                    </span>
                                </div>
                                <div class="st_mn_ct_mn_pd_g_ls_work uk-flex uk-flex-column uk-flex-middle uk-width-1-3@s uk-width-1-4@m">
                                    <a href="/work/8" class="st_mn_ct_mn_pd_g_ls_wk_img"><img src="./image/top/10.png" alt=""></a>
                                    <span class="st_mn_ct_mn_pd_g_ls_wk_title">
                                        ロゴ２
                                    </span>
                                </div>
                                <div class="st_mn_ct_mn_pd_g_ls_work uk-flex uk-flex-column uk-flex-middle uk-width-1-3@s uk-width-1-4@m">
                                    <a href="/work/14" class="st_mn_ct_mn_pd_g_ls_wk_img"><img src="./image/top/11.png" alt=""></a>
                                    <span class="st_mn_ct_mn_pd_g_ls_wk_title">
                                        作品集
                                    </span>
                                </div>
                            </section>
                        </div>

                        <!-- グループ：その他 -->
                        <div class="st_mn_ct_mn_pd_group uk-flex uk-flex-column uk-flex-middle">
                            <!-- グループタイトル -->
                            <div class="st_mn_ct_mn_pd_g_title uk-flex uk-flex-middle">
                                その他
                            </div>
                            <!-- グループリスト -->
                            <section class="st_mn_ct_mn_pd_g_list uk-flex" uk-grid>
                                <div class="st_mn_ct_mn_pd_g_ls_work uk-flex uk-flex-column uk-flex-middle uk-width-1-3@s uk-width-1-4@m">
                                    <a href="/work/10" class="st_mn_ct_mn_pd_g_ls_wk_img"><img src="./image/top/12.png" alt=""></a>
                                    <span class="st_mn_ct_mn_pd_g_ls_wk_title">
                                        名刺
                                    </span>
                                </div>
                                <div class="st_mn_ct_mn_pd_g_ls_work uk-flex uk-flex-column uk-flex-middle uk-width-1-3@s uk-width-1-4@m">
                                    <a href="/work/9" class="st_mn_ct_mn_pd_g_ls_wk_img"><img src="./image/top/13.png" alt=""></a>
                                    <span class="st_mn_ct_mn_pd_g_ls_wk_title">
                                        LINEスタンプ
                                    </span>
                                </div>
                                <div class="st_mn_ct_mn_pd_g_ls_work uk-flex uk-flex-column uk-flex-middle uk-width-1-3@s uk-width-1-4@m">
                                    <a href="/work/13" class="st_mn_ct_mn_pd_g_ls_wk_img"><img src="./image/top/14.png" alt=""></a>
                                    <span class="st_mn_ct_mn_pd_g_ls_wk_title">
                                        入浴剤
                                    </span>
                                </div>
                            </section>
                        </div>
                    </section>
                </div>
