<?php
$title   = 'HIPHOPかるたの箱';
$label   = '実際に遊べる！';
$labelColor = '#fab8e4';
$imgurl  = '../image/gallery/9.png';

$target  = 'HIPHOPカルチャーや遊び心のあるデザインを楽しみたい方';
$mokuteki = '実際に遊べるHIPHOPかるたの世界観が伝わる箱パッケージの制作';
$concept = 'ストリート感のあるタイポグラフィで、HIPHOPらしさを表現した箱デザイン';
$point   = '・木目調の背景と太いロゴで、力強いストリート感を演出\n・スプラッシュ表現をアクセントに入れ、HIPHOPらしい勢いを表現\n・箱側面にも説明を配置し、商品としての完成度を高めた';
$tool    = '・Adobe Illustrator\n・Adobe Photoshop';


$target_old  = '香り付きコスメを好む若年層';
$mokuteki_old = 'サイトのメインとなる飼い猫をモチーフに\n親しみやすく日常で使いやすいスタンプを制作';
$concept_old = 'かわいく親しみやすく、日常で使いやすい\nサイトのメインとなる飼い猫のスタンプ';
$point_old   = '・実際の猫の写真を使用し、\n　リアルでかわいらしい印象に\n・日常で使いやすい言葉を選び、実用性を重視\n・シンプルな構成で見やすく、使いやすいデザインに';
