<div class="flex-wrap">
					<section id="new">
						<h2>お知らせ</h2>
						<div class="list-free">
							<dl class="new">
								<dt><span class="icon-bg1">ターゲット</dt>
								<dd>　音楽や宇宙など、世界観のあるデザインを好む方</dd>
								<dt><span class="icon-bg2">目的</span></dt>
								<dd>　「自由」をテーマにしたTシャツデザインの制作</dd>
								<dt><span class="icon-bg1">コンセプト</span></dt>
								<dd>　「自由」をテーマに、宇宙と音楽で世界観を表現</dd>
								<dt><span class="icon-bg2">ポイント</dt>
								<dd>　・音符や「music」の文字を、宇宙を漂うように配置<br> 　・天の川を音楽の五線譜に見立てたデザイン<br> 　・モノトーンで統一し、シンプルかつ印象に残る表現</dd>
								<dt><span class="icon-bg1">使用ツール</span></dt>
								<dd>　・Adobe Illustrator</dd>
							</dl>
						</div>
					</section>
					<article>
						<h2>音と宇宙がつくる自由　-Tシャツ- <span class="option1">セット商品</span>
						</h2>
						<figure class="work">
							<img src="<?= htmlspecialchars($basePath, ENT_QUOTES, 'UTF-8') ?>image/gallery/2.png" alt="写真の説明を入れます">
						</figure>
				</div>
				</article>
				<p><a href="javascript:history.back()">&lt;&lt; 前のページに戻る</a></p>
