<div class="flex-wrap">
					<section id="new">
						<h2>お知らせ</h2>
						<div class="list-free">
							<dl class="new">
								<dt><span class="icon-bg1">ターゲット</dt>
								<dd>　名刺を交換する方</dd>
								<dt><span class="icon-bg2">目的</span></dt>
								<dd>　自身の情報を分かりやすく伝えるための名刺デザイン</dd>
								<dt><span class="icon-bg1">コンセプト</span></dt>
								<dd>　ナチュラルで親しみやすい印象の名刺</dd>
								<dt><span class="icon-bg2">ポイント</dt>
								<dd>　・やわらかい配色で、親しみやすい印象を表現<br> 　・猫のモチーフで個性を加え、印象に残るデザインに<br> 　・情報を整理し、見やすさと読みやすさを重視
								<dt><span class="icon-bg1">使用ツール</span></dt>
								<dd>　・Adobe Illustrator</dd>
							</dl>
						</div>
					</section>
					<article>
						<h2>名刺 <span class="option1">日常で使える</span>
						</h2>
						<figure class="work">
							<img src="<?= htmlspecialchars($basePath, ENT_QUOTES, 'UTF-8') ?>image/gallery/1.png" alt="写真の説明を入れます">
						</figure>
				</div>
				</article>
				<p><a href="javascript:history.back()">&lt;&lt; 前のページに戻る</a></p>
