<div class="flex-wrap">
					<section id="new">
						<h2>お知らせ</h2>
						<div class="list-free">
							<dl class="new">
								<dt><span class="icon-bg1">ターゲット</dt>
								<dd>　音楽やアートなど、世界観のあるデザインを好む方</dd>
								<dt><span class="icon-bg2">目的</span></dt>
								<dd>　「自由」をテーマにしたパンツデザインの制作</dd>
								<dt><span class="icon-bg1">コンセプト</span></dt>
								<dd>　深海から夜空へ広がる世界観を表現</dd>
								<dt><span class="icon-bg2">ポイント</dt>
								<dd>　・魚と鳥で、海から空への広がりを表現<br> 　・グラデーションで深海から夜空への変化を表現<br> 　・裾にピアノの鍵盤を配置し、音の広がりを演出
								<dt><span class="icon-bg1">使用ツール</span></dt>
								<dd>　・Adobe Illustrator</dd>
							</dl>
						</div>
					</section>
					<article>
						<h2>深海から夜空へ　-パンツ- <span class="option1">セット商品</span>
						</h2>
						<figure class="work">
							<img src="<?= htmlspecialchars($basePath, ENT_QUOTES, 'UTF-8') ?>image/gallery/11.png" alt="写真の説明を入れます">
						</figure>
				</div>
				</article>
				<p><a href="javascript:history.back()">&lt;&lt; 前のページに戻る</a></p>
