<div class="flex-wrap">
					<section id="new">
						<h2>お知らせ</h2>
						<div class="list-free">
							<dl class="new">
								<dt><span class="icon-bg1">ターゲット</dt>
								<dd>　香り付きコスメを好む若年層</dd>
								<dt><span class="icon-bg2">目的</span></dt>
								<dd>　サイトのメインとなる飼い猫をモチーフに<br> 　親しみやすく日常で使いやすいスタンプを制作</dd>
								<dt><span class="icon-bg1">コンセプト</span></dt>
								<dd>　かわいく親しみやすく、日常で使いやすい<br> 　サイトのメインとなる飼い猫のスタンプ</dd>
								<dt><span class="icon-bg2">ポイント</dt>
								<dd>　・実際の猫の写真を使用し、<br> 　　リアルでかわいらしい印象に<br> 　・日常で使いやすい言葉を選び、実用性を重視<br> 　・シンプルな構成で見やすく、使いやすいデザインに
								<dt><span class="icon-bg1">使用ツール</span></dt>
								<dd>　・Adobe Illustrator<br> 　・Adobe Photoshop </dd>
							</dl>
						</div>
					</section>
					<article>
						<h2>入浴剤 <span class="option1">春夏秋冬楽しめます。</span>
						</h2>
						<figure class="work">
							<img src="<?= htmlspecialchars($basePath, ENT_QUOTES, 'UTF-8') ?>image/gallery/12.png" alt="写真の説明を入れます">
						</figure>
				</div>
				</article>
				<p><a href="javascript:history.back()">&lt;&lt; 前のページに戻る</a></p>
