<div class="flex-wrap">
					<section id="new">
						<h2>お知らせ</h2>
						<div class="list-free">
							<dl class="new">
								<dt><span class="icon-bg1">ターゲット</dt>
								<dd>　ポートフォリオ閲覧者</dd>
								<dt><span class="icon-bg2">目的</span></dt>
								<dd>　ポートフォリオに使用するロゴの制作</dd>
								<dt><span class="icon-bg1">コンセプト</span></dt>
								<dd>　サイトの雰囲気に合わせたナチュラル系のロゴを制作</dd>
								<dt><span class="icon-bg2">ポイント</dt>
								<dd>　・上品な印象になるようなフォント選び<br> 　・ポートフォリオサイトの雰囲気に合わせ、<br> 　　ナチュラルで落ち着いた印象に
								<dt><span class="icon-bg1">使用ツール</span></dt>
								<dd>　・Adobe Illustrator<br> 　・Adobe Photoshop </dd>
							</dl>
						</div>
					</section>
					<article>
						<h2>サイトのロゴ２ <span class="option1">サイトに使われてます</span>
						</h2>
						<figure class="work">
							<img src="<?= htmlspecialchars($basePath, ENT_QUOTES, 'UTF-8') ?>image/gallery/13.png" alt="写真の説明を入れます">
						</figure>
				</div>
				</article>
				<p><a href="javascript:history.back()">&lt;&lt; 前のページに戻る</a></p>
